# Generated by Django 3.2.6 on 2022-06-14 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220612_0842'),
        ('users', '0002_notification'),
    ]

    operations = [
    ]
