# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-06-10 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0003_post_blog_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='blog_pic',
            new_name='blog_pics',
        ),
    ]
